/*
 * Copyright (C) 2020 BlueKitchen GmbH
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holders nor the names of
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 * 4. Any redistribution, use, or modification is done solely for
 *    personal benefit and not for any commercial purpose or for
 *    monetary gain.
 *
 * THIS SOFTWARE IS PROVIDED BY BLUEKITCHEN GMBH AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL BLUEKITCHEN
 * GMBH OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
 * THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * Please inquire about commercial licensing options at
 * contact@bluekitchen-gmbh.com
 *
 */

#define BTSTACK_FILE__ "hog_host_demo.c"

/* EXAMPLE_START(hog_host_demo): HID Host LE
 *
 * @text This example implements a minimal HID-over-GATT Host. It scans for LE HID devices, connects to it,
 * discovers the Characteristics relevant for the HID Service and enables Notifications on them.
 * It then dumps all Boot Keyboard and Mouse Input Reports
 */

#include <inttypes.h>
#include <stdio.h>
#include <btstack_tlv.h>

#include "btstack_config.h"
#include "btstack.h"

// hog_host_demo.gatt contains the declaration of the provided GATT Services + Characteristics
// hog_host_demo.h    contains the binary representation of gatt_browser.gatt
// it is generated by the build system by calling: $BTSTACK_ROOT/tool/compile_gatt.py hog_host_demo.gatt hog_host_demo.h
// it needs to be regenerated when the GATT Database declared in gatt_browser.gatt file is modified
#include "hog_host_demo.h"
#include "bt_example_common.h"
#include "pico/cyw43_arch.h"
#include "Common.h"

//--------------------------------------------------------------------+
// CONSTANTS & TYPES
//--------------------------------------------------------------------+
// Timeout constants
#define CONNECTION_TIMEOUT_MS 3000  // 3 seconds for connection attempt
#define SCAN_TIMEOUT_MS       5000  // 5 seconds for scanning
#define RECONNECT_DELAY_MS    300   // 300 ms recovery delay after disconnection before restarting scan/connect
#define LED_BLINKING_INTERVAL_MS 200 // 200 ms for LED blinking

// Connection parameters requested once the link is encrypted. Peripherals are
// free to advertise a slow, power-saving interval; for an input device the
// round trip is what the user feels, so ask for the shortest interval the LE
// spec allows a peripheral to be required to honour.
#define CONN_INTERVAL_MIN_UNITS 10  // x 1.25 ms = 12.5 ms
#define CONN_INTERVAL_MAX_UNITS 12  // x 1.25 ms = 15 ms
#define CONN_LATENCY_EVENTS     0   // no skipped connection events
#define CONN_TIMEOUT_UNITS      300 // x 10 ms = 3 s supervision timeout

// TAG to store remote device address and type in TLV
#define TLV_TAG_HOGD ((((uint32_t) 'H') << 24 ) | (((uint32_t) 'O') << 16) | (((uint32_t) 'G') << 8) | 'D')

// Cache of pending RPA lookups to preserve advertisement metadata across asynchronous SM events
#define MAX_PENDING_RPA_LOOKUPS 4

typedef struct {
    bd_addr_t addr;
    bool has_hid_service;
    bool in_use;
} pending_rpa_lookup_t;

typedef struct {
    bd_addr_t addr;
    bd_addr_type_t addr_type;
} le_device_addr_t;

typedef enum {
    W4_WORKING,
    W4_HID_DEVICE_FOUND,
    W4_CONNECTED,
    W4_ENCRYPTED,
    W4_HID_CLIENT_CONNECTED,
    READY,
    W4_TIMEOUT_THEN_SCAN,
    W4_TIMEOUT_THEN_RECONNECT,
} app_state_t;

//--------------------------------------------------------------------+
// GLOBAL & STATIC VARIABLES
//--------------------------------------------------------------------+
static app_state_t app_state;
static le_device_addr_t bonded_device;
static le_device_addr_t target_device;
static bool has_bonded_device = false;
static hci_con_handle_t connection_handle;
static uint16_t hids_cid;
static hid_protocol_mode_t protocol_mode = HID_PROTOCOL_MODE_REPORT;

static pending_rpa_lookup_t pending_rpa_lookups[MAX_PENDING_RPA_LOOKUPS];
static uint8_t pending_rpa_lookup_index = 0;

// GATT/HIDS: The whole HID report descriptor of the remote device is cached here and later
// handed to the USB host verbatim. Keyboards with media keys, multi-device
// switching or vendor collections run well past the 500 bytes the BTstack
// example assumes, and the surplus is silently dropped, so give it 2 KB.
static uint8_t hid_descriptor_storage[2048];

// Used to implement connection timeout and reconnect timer
static btstack_timer_source_t connection_timer;
static btstack_timer_source_t led_timer;

// Register for events from HCI/GAP and SM
static btstack_packet_callback_registration_t hci_event_callback_registration;
static btstack_packet_callback_registration_t sm_event_callback_registration;

// Used to store remote device in TLV
static const btstack_tlv_t * btstack_tlv_singleton_impl;
static void * btstack_tlv_singleton_context;

extern volatile bool g_usb_reinit_request;

//--------------------------------------------------------------------+
// FUNCTION PROTOTYPES
//--------------------------------------------------------------------+
// PUBLIC APIs & ENTRY POINTS
void ble_host_main(void);
bool is_ble_app_state_ready(void);
const uint8_t* get_ble_hid_report_descriptor_data(void);
uint16_t get_ble_hid_report_descriptor_len(void);

// INITIALIZATION
int btstack_main(int argc, const char * argv[]);

// EVENT HANDLERS
static void packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size);
static void sm_packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size);
static void handle_gatt_client_event(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size);

// CONNECTION & SCANNING CONTROL
static void hog_start_connect(void);
static void hog_connect(void);
static void hog_start_scan(void);
static void hog_scan_timeout(btstack_timer_source_t * ts);
static void hog_connection_timeout(btstack_timer_source_t * ts);
static void hog_reconnect_timeout(btstack_timer_source_t * ts);
static void handle_outgoing_connection_error(void);
static void request_hid_connection_parameters(void);
static bool is_resolvable_private_address(bd_addr_type_t addr_type, const bd_addr_t addr);
static bool adv_event_contains_hid_service(const uint8_t * packet);
static bool is_rpa_lookup_pending(const bd_addr_t addr);
static void clear_all_pending_rpa_lookups(void);
static void clear_pending_rpa_lookup(const bd_addr_t addr);
static void track_pending_rpa_lookup(const bd_addr_t addr, bool has_hid_service);
static bool get_and_clear_pending_rpa_has_hid_service(const bd_addr_t addr);

// HID REPORT HANDLING
static void hid_handle_input_report(uint8_t service_index, uint8_t report_id, const uint8_t * report, uint16_t report_len);

// LED BLINKING TIMER HANDLER
static void led_timer_handler(btstack_timer_source_t * ts);

//--------------------------------------------------------------------+
// PUBLIC APIs & ENTRY POINTS
//--------------------------------------------------------------------+

/**
 * @brief Main function for the BLE host task (runs on Core1).
 * @note This function initializes and runs the BTstack event loop.
 */
void ble_host_main(void)
{
    // Initialize BTstack for the current board
    (void)ble_bridge_bt_example_init();
    // Set up and start the main BTstack task
    ble_bridge_bt_example_main();
    // Enter the BTstack run loop
    btstack_run_loop_execute();
}

/**
 * @brief Check if the BLE application state is READY.
 * @return true if the application state is READY, false otherwise.
 */
bool is_ble_app_state_ready(void)
{
    return (READY == app_state) ? true : false;
}

/**
 * @brief Get the pointer to the HID Report Descriptor received via BLE.
 * @return Pointer to the HID Report Descriptor data.
 */
const uint8_t* get_ble_hid_report_descriptor_data(void)
{
    return hids_client_descriptor_storage_get_descriptor_data(hids_cid, 0);
}

/**
 * @brief Get the length of the HID Report Descriptor received via BLE.
 * @return Length of the HID Report Descriptor.
 */
uint16_t get_ble_hid_report_descriptor_len(void)
{
    return hids_client_descriptor_storage_get_descriptor_len(hids_cid, 0);
}

//--------------------------------------------------------------------+
// INITIALIZATION
//--------------------------------------------------------------------+

/**
 * @brief Initialize and start the BTstack setup for HID host.
 * @param argc Argument count.
 * @param argv Argument vector.
 * @return Status code (0 on success).
 */
int btstack_main(int argc, const char * argv[])
{
    (void)argc;
    (void)argv;

    l2cap_init();

    // setup SM: No Input No Output
    sm_init();
    sm_set_io_capabilities(IO_CAPABILITY_NO_INPUT_NO_OUTPUT);
    sm_set_authentication_requirements(SM_AUTHREQ_SECURE_CONNECTION | SM_AUTHREQ_BONDING);

    gatt_client_init();

    // setup ATT server - only needed if LE Peripheral does ATT queries on its own, e.g. Android and iOS
    att_server_init(profile_data, NULL, NULL);

    hids_client_init(hid_descriptor_storage, sizeof(hid_descriptor_storage));

    // register for events from HCI
    hci_event_callback_registration.callback = &packet_handler;
    hci_add_event_handler(&hci_event_callback_registration);

    // register for events from Security Manager
    sm_event_callback_registration.callback = &sm_packet_handler;
    sm_add_event_handler(&sm_event_callback_registration);

    app_state = W4_WORKING;

    // Start LED blinking timer on BTstack run loop (Core 1)
    btstack_run_loop_set_timer_handler(&led_timer, &led_timer_handler);
    btstack_run_loop_set_timer(&led_timer, LED_BLINKING_INTERVAL_MS);
    btstack_run_loop_add_timer(&led_timer);

    // Turn on the device
    hci_power_control(HCI_POWER_ON);
    return 0;
}

//--------------------------------------------------------------------+
// EVENT HANDLERS
//--------------------------------------------------------------------+

/**
 * @brief HCI and GAP event packet handler.
 * @param packet_type Type of incoming packet.
 * @param channel Channel ID.
 * @param packet Pointer to packet payload.
 * @param size Size of packet.
 */
static void packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size)
{
    UNUSED(channel);
    UNUSED(size);
    uint8_t event;

    switch (packet_type) {
        case HCI_EVENT_PACKET:
            event = hci_event_packet_get_type(packet);
            switch (event) {
                case BTSTACK_EVENT_STATE:
                    if (btstack_event_state_get_state(packet) != HCI_STATE_WORKING) break;
                    btstack_assert(app_state == W4_WORKING);
                    
                    hog_start_connect();
                    break;
                case GAP_EVENT_ADVERTISING_REPORT:
                {
                    if (app_state != W4_HID_DEVICE_FOUND) break;
                    
                    bd_addr_t adv_addr;
                    gap_event_advertising_report_get_address(packet, adv_addr);
                    bd_addr_type_t raw_addr_type = gap_event_advertising_report_get_address_type(packet);
                    // Normalize address type (0=Public, 1=Random, 2=Public Identity -> 0, 3=Random Identity -> 1)
                    bd_addr_type_t adv_addr_type = (bd_addr_type_t)(raw_addr_type & 1);
                    bool has_hid_service = adv_event_contains_hid_service(packet);
                    
                    // 1. If bonded device exists and incoming address is an RPA, resolve address against IRK in le_device_db
                    // Skip duplicated lookups if address is already being resolved
                    if (has_bonded_device && is_resolvable_private_address(adv_addr_type, adv_addr)) {
                        if (!is_rpa_lookup_pending(adv_addr)) {
                            track_pending_rpa_lookup(adv_addr, has_hid_service);
                            sm_address_resolution_lookup(adv_addr_type, adv_addr);
                        }
                        break;
                    }

                    // 2. Direct match with bonded identity address (Public / Static Random address)
                    if (has_bonded_device && (memcmp(adv_addr, bonded_device.addr, 6) == 0)) {
                        BLE_LOG("Found bonded device %s directly, connecting...\n", bd_addr_to_str(adv_addr));
                        btstack_run_loop_remove_timer(&connection_timer);
                        gap_stop_scan();

                        memcpy(target_device.addr, adv_addr, 6);
                        target_device.addr_type = adv_addr_type;
                        hog_connect();
                        break;
                    }

                    // 3. New HID Device Advertisement (Device in pairing mode or active HID advertising)
                    if (has_hid_service) {
                        BLE_LOG("Found HID device %s (type %u), connecting...\n", bd_addr_to_str(adv_addr), adv_addr_type);
                        btstack_run_loop_remove_timer(&connection_timer);
                        gap_stop_scan();

                        memcpy(target_device.addr, adv_addr, 6);
                        target_device.addr_type = adv_addr_type;
                        hog_connect();
                        break;
                    }
                    break;
                }
                case HCI_EVENT_DISCONNECTION_COMPLETE:
                {
                    uint8_t reason = hci_event_disconnection_complete_get_reason(packet);
                    const char * reason_str = "Unknown";
                    switch (reason) {
                        case ERROR_CODE_CONNECTION_TIMEOUT:
                            reason_str = "Connection Timeout (0x08)";
                            break;
                        case ERROR_CODE_REMOTE_USER_TERMINATED_CONNECTION:
                            reason_str = "Remote User Terminated / Keyboard disconnected (0x13)";
                            break;
                        case ERROR_CODE_REMOTE_DEVICE_TERMINATED_CONNECTION_DUE_TO_LOW_RESOURCES:
                            reason_str = "Remote Device Low Resources (0x14)";
                            break;
                        case ERROR_CODE_REMOTE_DEVICE_TERMINATED_CONNECTION_DUE_TO_POWER_OFF:
                            reason_str = "Remote Device Power Off (0x15)";
                            break;
                        case ERROR_CODE_CONNECTION_TERMINATED_BY_LOCAL_HOST:
                            reason_str = "Local Host Terminated (0x16)";
                            break;
                        case ERROR_CODE_LMP_RESPONSE_TIMEOUT_LL_RESPONSE_TIMEOUT:
                            reason_str = "LMP/LL Response Timeout (0x22)";
                            break;
                        case ERROR_CODE_UNACCEPTABLE_CONNECTION_PARAMETERS:
                            reason_str = "Unacceptable Connection Parameters (0x3B)";
                            break;
                        default:
                            break;
                    }
                    connection_handle = HCI_CON_HANDLE_INVALID;
                    BLE_LOG("Disconnected (Reason: 0x%02x - %s), restarting in %d ms...\n", reason, reason_str, RECONNECT_DELAY_MS);
                    
                    // Fix: Ensure timer and pending RPA lookups are cleared upon disconnection before starting over
                    btstack_run_loop_remove_timer(&connection_timer);
                    clear_all_pending_rpa_lookups();

                    // Wait a short delay before restarting the connection loop to allow both BLE controller and remote peripheral to stabilize
                    app_state = W4_WORKING;
                    btstack_run_loop_set_timer(&connection_timer, RECONNECT_DELAY_MS);
                    btstack_run_loop_set_timer_handler(&connection_timer, &hog_reconnect_timeout);
                    btstack_run_loop_add_timer(&connection_timer);
                    break;
                }
                case HCI_EVENT_META_GAP:
                    // wait for connection complete
                    if (hci_event_gap_meta_get_subevent_code(packet) != GAP_SUBEVENT_LE_CONNECTION_COMPLETE) break;
                    if (app_state != W4_CONNECTED) return;
                    btstack_run_loop_remove_timer(&connection_timer);
                    {
                        uint8_t status = gap_subevent_le_connection_complete_get_status(packet);
                        if (status != ERROR_CODE_SUCCESS) {
                            BLE_LOG("LE Connection failed (Status: 0x%02x). Restarting scan...\n", status);
                            connection_handle = HCI_CON_HANDLE_INVALID;
                            hog_start_scan();
                            break;
                        }
                    }
                    connection_handle = gap_subevent_le_connection_complete_get_connection_handle(packet);
                    // request security
                    app_state = W4_ENCRYPTED;
                    sm_request_pairing(connection_handle);
                    break;
                default:
                    break;
            }
            break;
        default:
            break;
    }
}

/**
 * @brief Security Manager (SM) packet handler for pairing, identity, and re-encryption events.
 * @param packet_type Type of incoming packet.
 * @param channel Channel ID.
 * @param packet Pointer to packet payload.
 * @param size Size of packet.
 */
static void sm_packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size)
{
    UNUSED(channel);
    UNUSED(size);

    if (packet_type != HCI_EVENT_PACKET) return;

    bool connect_to_service = false;

    switch (hci_event_packet_get_type(packet)) {
        case SM_EVENT_JUST_WORKS_REQUEST:
            BLE_LOG("Just works requested\n");
            sm_just_works_confirm(sm_event_just_works_request_get_handle(packet));
            break;
        case SM_EVENT_NUMERIC_COMPARISON_REQUEST:
            BLE_LOG("Confirming numeric comparison: %06"PRIu32"\n", sm_event_numeric_comparison_request_get_passkey(packet));
            sm_numeric_comparison_confirm(sm_event_numeric_comparison_request_get_handle(packet));
            break;
        case SM_EVENT_PASSKEY_DISPLAY_NUMBER:
            BLE_LOG("Display Passkey: %06"PRIu32"\n", sm_event_passkey_display_number_get_passkey(packet));
            break;
        case SM_EVENT_IDENTITY_RESOLVING_SUCCEEDED:
        {
            bd_addr_t resolved_identity_addr;
            bd_addr_t rpa_addr;
            sm_event_identity_resolving_succeeded_get_identity_address(packet, resolved_identity_addr);
            bd_addr_type_t resolved_identity_type = sm_event_identity_resolving_succeeded_get_identity_addr_type(packet);
            sm_event_identity_resolving_succeeded_get_address(packet, rpa_addr);
            bd_addr_type_t rpa_addr_type = (bd_addr_type_t)(sm_event_identity_resolving_succeeded_get_addr_type(packet) & 1);
            
            // Clear pending tracking entry for this RPA
            clear_pending_rpa_lookup(rpa_addr);

            BLE_LOG("SM: RPA %s resolved to Identity %s (type %u)\n", 
                    bd_addr_to_str(rpa_addr), bd_addr_to_str(resolved_identity_addr), resolved_identity_type);
            
            if (has_bonded_device && (memcmp(resolved_identity_addr, bonded_device.addr, 6) == 0)) {
                if (app_state == W4_HID_DEVICE_FOUND) {
                    BLE_LOG("Resolved RPA matches bonded peripheral! Connecting to RPA %s...\n", bd_addr_to_str(rpa_addr));
                    btstack_run_loop_remove_timer(&connection_timer);
                    gap_stop_scan();
                    memcpy(target_device.addr, rpa_addr, 6);
                    target_device.addr_type = rpa_addr_type;
                    hog_connect();
                }
            }
            break;
        }
        case SM_EVENT_IDENTITY_RESOLVING_FAILED:
        {
            bd_addr_t rpa_addr;
            sm_event_identity_resolving_failed_get_address(packet, rpa_addr);
            bd_addr_type_t rpa_addr_type = (bd_addr_type_t)(sm_event_identity_resolving_failed_get_addr_type(packet) & 1);
            bool adv_had_hid = get_and_clear_pending_rpa_has_hid_service(rpa_addr);

            // If the unresolved RPA explicitly contains the HID service UUID or HID Appearance,
            // connect as new device or re-pairing device.
            if (adv_had_hid && (app_state == W4_HID_DEVICE_FOUND)) {
                BLE_LOG("SM: Unresolved RPA %s has HID service, connecting as new device...\n", bd_addr_to_str(rpa_addr));
                btstack_run_loop_remove_timer(&connection_timer);
                gap_stop_scan();
                memcpy(target_device.addr, rpa_addr, 6);
                target_device.addr_type = rpa_addr_type;
                hog_connect();
            } else {
                // BLE_LOG("SM: RPA %s not resolved & no HID service (ignored)\n", bd_addr_to_str(rpa_addr));
            }
            break;
        }
        case SM_EVENT_IDENTITY_CREATED:
        {
            bd_addr_t identity_addr;
            sm_event_identity_created_get_identity_address(packet, identity_addr);
            bd_addr_type_t identity_addr_type = sm_event_identity_created_get_identity_addr_type(packet);
            BLE_LOG("SM: Identity created: %s (type %u)\n", bd_addr_to_str(identity_addr), identity_addr_type);
            memcpy(bonded_device.addr, identity_addr, 6);
            bonded_device.addr_type = identity_addr_type;
            has_bonded_device = true;
            break;
        }
        case SM_EVENT_PAIRING_COMPLETE:
            switch (sm_event_pairing_complete_get_status(packet)){
                case ERROR_CODE_SUCCESS:
                    BLE_LOG("Pairing complete, success\n");
                    request_hid_connection_parameters();
                    connect_to_service = true;
                    break;
                case ERROR_CODE_CONNECTION_TIMEOUT:
                    BLE_LOG("Pairing failed, timeout\n");
                    handle_outgoing_connection_error();
                    break;
                case ERROR_CODE_PIN_OR_KEY_MISSING:
                case ERROR_CODE_AUTHENTICATION_FAILURE:
                    BLE_LOG("Pairing failed (Key missing/Auth failure: 0x%02x). Clearing bond & restarting...\n", 
                            sm_event_pairing_complete_get_status(packet));
                    btstack_tlv_get_instance(&btstack_tlv_singleton_impl, &btstack_tlv_singleton_context);
                    if (btstack_tlv_singleton_impl) {
                        btstack_tlv_singleton_impl->delete_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD);
                    }
                    gap_delete_bonding(target_device.addr_type, target_device.addr);
                    if (has_bonded_device) {
                        gap_delete_bonding(bonded_device.addr_type, bonded_device.addr);
                    }
                    has_bonded_device = false;
                    handle_outgoing_connection_error();
                    break;
                default:
                    BLE_LOG("Pairing failed, status 0x%02x\n", sm_event_pairing_complete_get_status(packet));
                    handle_outgoing_connection_error();
                    break;
            }
            break;
        case SM_EVENT_REENCRYPTION_COMPLETE:
            BLE_LOG("Re-encryption complete, success\n");
            request_hid_connection_parameters();
            connect_to_service = true;
            break;
        default:
            break;
    }

    if (connect_to_service){
        // continue - query primary services
        BLE_LOG("Search for HID service.\n");
        app_state = W4_HID_CLIENT_CONNECTED;
        hids_client_connect(connection_handle, handle_gatt_client_event, protocol_mode, &hids_cid);
    }
}

/**
 * @brief Handle GATT Client events dependent on current application state.
 * @param packet_type Type of incoming packet.
 * @param channel Channel ID.
 * @param packet Pointer to packet payload.
 * @param size Size of packet.
 */
static void handle_gatt_client_event(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size)
{
    UNUSED(packet_type);
    UNUSED(channel);
    UNUSED(size);

    uint8_t status;

    if (hci_event_packet_get_type(packet) != HCI_EVENT_GATTSERVICE_META){
        return;
    }
    
    switch (hci_event_gattservice_meta_get_subevent_code(packet)){
        case GATTSERVICE_SUBEVENT_HID_SERVICE_CONNECTED:
            status = gattservice_subevent_hid_service_connected_get_status(packet);
            switch (status){
                case ERROR_CODE_SUCCESS:
                    BLE_LOG("HID service client connected, found %d services\n", 
                        gattservice_subevent_hid_service_connected_get_num_instances(packet));
        
                    if (!has_bonded_device || (!is_resolvable_private_address(target_device.addr_type, target_device.addr) && memcmp(bonded_device.addr, target_device.addr, 6) != 0)) {
                        if (!is_resolvable_private_address(target_device.addr_type, target_device.addr)) {
                            memcpy(&bonded_device, &target_device, sizeof(bonded_device));
                            bonded_device.addr_type = (bd_addr_type_t)(bonded_device.addr_type & 1);
                        }
                        has_bonded_device = true;
                    }

                    // store bonded identity address in TLV
                    btstack_tlv_get_instance(&btstack_tlv_singleton_impl, &btstack_tlv_singleton_context);
                    if (btstack_tlv_singleton_impl){
                        btstack_tlv_singleton_impl->store_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD, (const uint8_t *) &bonded_device, sizeof(bonded_device));
                        BLE_LOG("Stored bonded identity %s (type %u) in TLV\n", bd_addr_to_str(bonded_device.addr), bonded_device.addr_type);
                    }
                    // done
                    BLE_LOG("Ready - please start typing or mousing..\n");
                    if (app_state != READY) {
                        app_state = READY;
                        // Re-initialize the USB device to make the USB host re-acquire the descriptor.
                        // This flag is referenced by USB task.
                        g_usb_reinit_request = true;
                    }
                    break;
                default:
                    BLE_LOG("HID service client connection failed, status 0x%02x.\n", status);
                    handle_outgoing_connection_error();
                    break;
            }
            break;

        case GATTSERVICE_SUBEVENT_HID_SERVICE_DISCONNECTED:
            BLE_LOG("HID service client disconnected\n");
            break;

        case GATTSERVICE_SUBEVENT_HID_REPORT:
            hid_handle_input_report(
                gattservice_subevent_hid_report_get_service_index(packet),
                gattservice_subevent_hid_report_get_report_id(packet), 
                gattservice_subevent_hid_report_get_report(packet), 
                gattservice_subevent_hid_report_get_report_len(packet));
            break;

        default:
            break;
    }
}

//--------------------------------------------------------------------+
// CONNECTION & SCANNING CONTROL
//--------------------------------------------------------------------+

/**
 * @brief Start connecting after boot up: load bonded device if present, then always start scanning.
 */
static void hog_start_connect(void)
{
    // check if we have a bonded device
    btstack_tlv_get_instance(&btstack_tlv_singleton_impl, &btstack_tlv_singleton_context);
    if (btstack_tlv_singleton_impl){
        int len = btstack_tlv_singleton_impl->get_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD, (uint8_t *) &bonded_device, sizeof(bonded_device));
        if (len == sizeof(bonded_device)){
            has_bonded_device = true;
            BLE_LOG("Bonded device loaded (%s, type %u). Starting scan...\n", 
                    bd_addr_to_str(bonded_device.addr), bonded_device.addr_type);
        } else {
            has_bonded_device = false;
        }
    } else {
        has_bonded_device = false;
    }
    // Always start scanning to reliably discover RPA or public advertising without blocking
    hog_start_scan();
}

/**
 * @brief Connect to target device with a connection timeout timer.
 */
static void hog_connect(void)
{
    BLE_LOG("Connecting to device %s (type %u, Timeout %dms)...\n", 
            bd_addr_to_str(target_device.addr), target_device.addr_type, CONNECTION_TIMEOUT_MS);
    
    // Fix: Remove timer before adding. If a previous timer (like scan timeout) is still active, 
    // btstack_run_loop_add_timer would trigger an assertion failure.
    btstack_run_loop_remove_timer(&connection_timer);

    // Set timer for connection attempt
    btstack_run_loop_set_timer(&connection_timer, CONNECTION_TIMEOUT_MS);
    btstack_run_loop_set_timer_handler(&connection_timer, &hog_connection_timeout);
    btstack_run_loop_add_timer(&connection_timer);
    
    app_state = W4_CONNECTED;
    gap_connect(target_device.addr, target_device.addr_type);
}

/**
 * @brief Start scanning for LE HID devices.
 */
static void hog_start_scan(void)
{
    BLE_LOG("Scanning for LE HID devices (Timeout %dms)...\n", SCAN_TIMEOUT_MS);
    app_state = W4_HID_DEVICE_FOUND;

    // Fix: Remove timer before adding to prevent assertion if scan is restarted during reconnection
    btstack_run_loop_remove_timer(&connection_timer);

    // Set timer to refresh scanning
    btstack_run_loop_set_timer(&connection_timer, SCAN_TIMEOUT_MS);
    btstack_run_loop_set_timer_handler(&connection_timer, &hog_scan_timeout);
    btstack_run_loop_add_timer(&connection_timer);

    // Passive scanning, 100% (scan interval = scan window)
    gap_set_scan_parameters(0,48,48);
    gap_start_scan();
}

/**
 * @brief Handle scan timeout by restarting scan.
 * @param ts Pointer to timer source structure.
 */
static void hog_scan_timeout(btstack_timer_source_t * ts)
{
    UNUSED(ts);
    if (app_state != W4_HID_DEVICE_FOUND) return;
    BLE_LOG("Scan timeout. Refreshing scan...\n");
    hog_start_scan();
}

/**
 * @brief Handle connection timeout by cancelling connection attempt and restarting scan.
 * @param ts Pointer to timer source structure.
 */
static void hog_connection_timeout(btstack_timer_source_t * ts)
{
    UNUSED(ts);
    BLE_LOG("Connection timeout. Switching to scan...\n");
    gap_connect_cancel();
    hog_start_scan();
}

/**
 * @brief Handle reconnection delay timer callback after disconnection.
 * @param ts Pointer to timer source structure.
 */
static void hog_reconnect_timeout(btstack_timer_source_t * ts)
{
    UNUSED(ts);
    hog_start_connect();
}

/**
 * @brief Handle connection error by disconnecting and restarting scan.
 */
static void handle_outgoing_connection_error(void)
{
    BLE_LOG("Error occurred, disconnect and start over\n");
    if (connection_handle != HCI_CON_HANDLE_INVALID) {
        gap_disconnect(connection_handle);
        // Do not call hog_start_scan() synchronously here; HCI_EVENT_DISCONNECTION_COMPLETE
        // will handle timer clearing and clean restart after controller disconnection.
    } else {
        hog_start_scan();
    }
}

/**
 * @brief Request optimized connection parameters for HID device.
 */
static void request_hid_connection_parameters(void)
{
    if (connection_handle == HCI_CON_HANDLE_INVALID) return;
    gap_request_connection_parameter_update(connection_handle,
                                             CONN_INTERVAL_MIN_UNITS,
                                             CONN_INTERVAL_MAX_UNITS,
                                             CONN_LATENCY_EVENTS,
                                             CONN_TIMEOUT_UNITS);
}

/**
 * @brief Check if advertising address is a Resolvable Private Address (RPA).
 * @param addr_type Address type.
 * @param addr Bluetooth address.
 * @return true if address is an RPA, false otherwise.
 */
static bool is_resolvable_private_address(bd_addr_type_t addr_type, const bd_addr_t addr)
{
    // RPA is a Random Address where top two bits are 01b (0x40 - 0x7F)
    return (addr_type == BD_ADDR_TYPE_LE_RANDOM) && ((addr[0] & 0xC0) == 0x40);
}

/**
 * @brief Check if advertising event packet contains HID service UUID or HID Appearance.
 * @param packet Pointer to advertising report packet.
 * @return true if HID service UUID or HID Appearance is found, false otherwise.
 */
static bool adv_event_contains_hid_service(const uint8_t * packet)
{
    const uint8_t * ad_data = gap_event_advertising_report_get_data(packet);
    uint8_t ad_len = gap_event_advertising_report_get_data_length(packet);
    if (ad_data_contains_uuid16(ad_len, ad_data, ORG_BLUETOOTH_SERVICE_HUMAN_INTERFACE_DEVICE)) {
        return true;
    }
    // Check Appearance AD structure (AD Type 0x19) for HID Categories (0x03C0 - 0x03CF)
    for (int i = 0; i + 3 <= ad_len;) {
        uint8_t len = ad_data[i];
        if (len == 0) break;
        if (i + 1 + len > ad_len) break;
        uint8_t type = ad_data[i + 1];
        if (type == 0x19 && len >= 3) {
            uint16_t appearance = (uint16_t)ad_data[i + 2] | ((uint16_t)ad_data[i + 3] << 8);
            if (appearance >= 0x03C0 && appearance <= 0x03CF) {
                return true;
            }
        }
        i += 1 + len;
    }
    return false;
}

/**
 * @brief Check if an RPA address resolution is already in progress.
 * @param addr RPA address.
 * @return true if address is already tracked and pending, false otherwise.
 */
static bool is_rpa_lookup_pending(const bd_addr_t addr)
{
    for (int i = 0; i < MAX_PENDING_RPA_LOOKUPS; i++) {
        if (pending_rpa_lookups[i].in_use && memcmp(pending_rpa_lookups[i].addr, addr, 6) == 0) {
            return true;
        }
    }
    return false;
}

/**
 * @brief Clear all pending RPA lookup records (e.g. upon disconnection).
 */
static void clear_all_pending_rpa_lookups(void)
{
    for (int i = 0; i < MAX_PENDING_RPA_LOOKUPS; i++) {
        pending_rpa_lookups[i].in_use = false;
    }
}

/**
 * @brief Clear a specific pending RPA lookup record upon resolution success.
 * @param addr RPA address.
 */
static void clear_pending_rpa_lookup(const bd_addr_t addr)
{
    for (int i = 0; i < MAX_PENDING_RPA_LOOKUPS; i++) {
        if (pending_rpa_lookups[i].in_use && memcmp(pending_rpa_lookups[i].addr, addr, 6) == 0) {
            pending_rpa_lookups[i].in_use = false;
        }
    }
}

/**
 * @brief Track an outgoing RPA address resolution request with its advertisement HID presence.
 * @param addr RPA address.
 * @param has_hid_service true if advertisement payload contained HID service UUID.
 */
static void track_pending_rpa_lookup(const bd_addr_t addr, bool has_hid_service)
{
    // If already exists in table, update the entry in place
    for (int i = 0; i < MAX_PENDING_RPA_LOOKUPS; i++) {
        if (pending_rpa_lookups[i].in_use && memcmp(pending_rpa_lookups[i].addr, addr, 6) == 0) {
            pending_rpa_lookups[i].has_hid_service = has_hid_service;
            return;
        }
    }

    memcpy(pending_rpa_lookups[pending_rpa_lookup_index].addr, addr, 6);
    pending_rpa_lookups[pending_rpa_lookup_index].has_hid_service = has_hid_service;
    pending_rpa_lookups[pending_rpa_lookup_index].in_use = true;
    pending_rpa_lookup_index = (pending_rpa_lookup_index + 1) % MAX_PENDING_RPA_LOOKUPS;
}

/**
 * @brief Retrieve and consume the HID advertisement status for an unresolved RPA.
 * @param addr RPA address.
 * @return true if advertisement contained HID service UUID, false otherwise.
 */
static bool get_and_clear_pending_rpa_has_hid_service(const bd_addr_t addr)
{
    for (int i = 0; i < MAX_PENDING_RPA_LOOKUPS; i++) {
        if (pending_rpa_lookups[i].in_use && memcmp(pending_rpa_lookups[i].addr, addr, 6) == 0) {
            pending_rpa_lookups[i].in_use = false;
            return pending_rpa_lookups[i].has_hid_service;
        }
    }
    return false;
}

//--------------------------------------------------------------------+
// HID REPORT HANDLING
//--------------------------------------------------------------------+

/**
 * @brief Process and enqueue received BLE HID input report.
 * @param service_index Index of the HID service.
 * @param report_id Report ID of the input report.
 * @param report Pointer to report data.
 * @param report_len Length of report data.
 */
static void hid_handle_input_report(uint8_t service_index, uint8_t report_id, const uint8_t * report, uint16_t report_len)
{
    // If an input report is received while not yet in READY state (e.g. fast reconnect),
    // update app_state to READY and request USB re-init so LED state becomes READY.
    if (app_state != READY) {
        BLE_LOG("HID report received in state %d. Forcing app_state to READY.\n", app_state);
        app_state = READY;
        g_usb_reinit_request = true;
    }
    
    // Enqueue the raw report for the USB task.
    // The USB HID task manages transmission to the host.
    static ST_HID_RPT stHidRpt; // Change local variable to static to use static memory (data area) instead of stack, preventing stack overflow.

    stHidRpt.report_id  = report_id;
    stHidRpt.report_len = report_len;  
    // Prevent buffer overflow if the report is larger than the buffer
    if (stHidRpt.report_len > CMN_HID_RPT_DATA_SIZE) {
        stHidRpt.report_len = CMN_HID_RPT_DATA_SIZE;
    }
    memcpy(stHidRpt.report, report, stHidRpt.report_len);
    if (!CMN_Enqueue(CMN_QUE_KIND_HID_RPT, &stHidRpt)) {
        // Queue is full
    }
    return;
}

//--------------------------------------------------------------------+
// LED BLINKING TIMER HANDLER
//--------------------------------------------------------------------+

/**
 * @brief Periodic timer callback executed on Core 1 (BTstack run loop) to drive the status LED.
 * @param ts Pointer to timer source structure.
 */
static void led_timer_handler(btstack_timer_source_t * ts)
{
    static bool led_state = false;

    if (app_state == READY) {
        // Turn on LED continuously when in READY state
        if (!led_state) {
            cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, true);
            led_state = true;
        }
    } else {
        // Blink LED every 200ms when not connected / connecting
        led_state = !led_state;
        cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, led_state);
    }

    // Re-arm the timer
    btstack_run_loop_set_timer(ts, LED_BLINKING_INTERVAL_MS);
    btstack_run_loop_add_timer(ts);
}

/* EXAMPLE_END */
